# Generated by Django 3.2.7 on 2021-09-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
                ('property', models.CharField(max_length=15)),
                ('idx', models.PositiveIntegerField()),
                ('docstatus', models.PositiveIntegerField()),
                ('parent', models.CharField(max_length=25)),
                ('parenttype', models.CharField(max_length=25)),
                ('creation', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
