# Generated by Django 3.2.7 on 2021-09-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
