# Generated by Django 3.2.7 on 2021-09-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='idx',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parent',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parenttype',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
