# Generated by Django 3.2.7 on 2021-09-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='modified_by',
            field=models.CharField(max_length=50),
        ),
    ]
